const _ = '[A-Z][a-z]',
  s = `^${_}+(${_}+)?`,
  S = [
    'Thin',
    'Hairline',
    'ExtraLight',
    'UltraLight',
    'Light',
    'Regular',
    'Medium',
    'SemiBold',
    'DemiBold',
    'Bold',
    'ExtraBold',
    'UltraBold',
    'Black',
    'Heavy',
    'ExtraBlack',
    'UltraBlack',
  ].join('|'),
  G = ['otf', 'ttf', 'woff', 'woff2'].join('|'),
  r = `(${s})`,
  T = `(${S})`,
  c = `(${G})$`,
  w = new RegExp(`${r}-${T}\\.${c}`),
  n = String.raw`(?:_|__|-|\s)`,
  $ = new RegExp(`${n}?(italic)`, 'i'),
  a = new RegExp(`${n}?(var)`, 'i'),
  g = new RegExp(String.raw`^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$`),
  i = new RegExp(String.raw`^[\sA-Za-zЁА-яё]+$`),
  I = new RegExp(String.raw`^\+[\d-]+$`),
  L = new RegExp(String.raw`^\S+$`, 'i'),
  N = '.html',
  R = '.pug',
  A = {
    HTML_EXTENSION_REGEX: N,
    PUG_EXTENSION_REGEX: R,
    FILE_EXTENSION_REGEX: new RegExp(String.raw`\.[^.]+$`),
    JS_EXTENSION_REGEX: new RegExp(String.raw`\.js$`),
    PUG_EXTENSION_REGEX_REGEX: new RegExp(`${R}$`),
    SCSS_EXTENSION_REGEX: new RegExp(String.raw`\.s[ac]ss$`),
    NODE_MODULES_REGEX: new RegExp('node_modules'),
  },
  O = { ALL_REGEX: new RegExp(String.raw`^\d+$`) },
  x = { RU_REGEX: new RegExp(String.raw`^\+7 \((9\d{2,3})\) \d{3}-\d{2}-\d{2}$`) },
  E = '[a-z0-9]',
  t = String.raw`?\[(.*)\]`,
  e = String.raw`?\.(.*)`,
  X = '--',
  o = '__',
  l = {
    bem: {
      BLOCK_REGEX: `[a-z]${E}*(-${E}+)`,
      ELEMENT_REGEX: `(${o}${E}+(-${E}+)*)`,
      MODIFIER_REGEX: `(${X}${E}+(-${E}+)*)`,
    },
    nested: {
      ATTRIBUTE_REGEX: t,
      CLASS_REGEX: e,
      ELEMENT_REGEX: o,
      MODIFIER_REGEX: X,
    },
    child: { ATTRIBUTE_REGEX: `${t} &`, CLASS_REGEX: `${e} &` },
  };
export {
  g as EMAIL_REGEX,
  w as FONT_FILE_NAME_REGEX,
  $ as ITALIC_REGEX,
  i as LATIN_AND_CYRILLIC_WITH_SPACES_REGEX,
  I as NOT_SEPARATE_REGEX,
  L as NOT_SPACE_REGEX,
  a as VARIABLE_FONT_REGEX,
  A as extensions,
  O as numbers,
  x as phones,
  l as selectors,
};
